name: 'dev'
run-name: ${{ github.actor }} testing
on:
  push:
    branches: 
      - hw1
      - hw2

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: cmake -S . -B .
      - run: cmake --build .
      - run: cmake --build . --target test
      - run: ctest 