name: 'dev'
run-name: ${{ github.actor }} testing hw2
# on: [create]
# on:
#   create:
#     tags: releases/[1-9]+.[0-9]+.[0-9].
# on:
  # push:
    # tags: releases/[1-9]+.[0-9]+.[0-9].
    # branches: master
on:
  push:
    branches: 
      - master
      # - release
    # tags: 
    #   - release/v[0-9]+.[0-9]+.[0-9].
    #   - release*

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: cmake -S . -B build
      - run: cmake --build build
      - run: cmake --build build --target test